
package trng.loan.eligibility.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LoanEligibilityService", targetNamespace = "http://www.example.org/LoanEligibilityService/", wsdlLocation = "file:/C:/Users/sandeep%20madineni/Desktop/New%20folder%20(4)/soapwenservice/src/main/resources/LoanEligibilityService.wsdl")
public class LoanEligibilityService_Service
    extends Service
{

    private final static URL LOANELIGIBILITYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(trng.loan.eligibility.service.LoanEligibilityService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = trng.loan.eligibility.service.LoanEligibilityService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/sandeep%20madineni/Desktop/New%20folder%20(4)/soapwenservice/src/main/resources/LoanEligibilityService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/sandeep%20madineni/Desktop/New%20folder%20(4)/soapwenservice/src/main/resources/LoanEligibilityService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOANELIGIBILITYSERVICE_WSDL_LOCATION = url;
    }

    public LoanEligibilityService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanEligibilityService_Service() {
        super(LOANELIGIBILITYSERVICE_WSDL_LOCATION, new QName("http://www.example.org/LoanEligibilityService/", "LoanEligibilityService"));
    }

    /**
     * 
     * @return
     *     returns LoanEligibilityService
     */
    @WebEndpoint(name = "LoanEligibilityServiceSOAP")
    public LoanEligibilityService getLoanEligibilityServiceSOAP() {
        return super.getPort(new QName("http://www.example.org/LoanEligibilityService/", "LoanEligibilityServiceSOAP"), LoanEligibilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanEligibilityService
     */
    @WebEndpoint(name = "LoanEligibilityServiceSOAP")
    public LoanEligibilityService getLoanEligibilityServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/LoanEligibilityService/", "LoanEligibilityServiceSOAP"), LoanEligibilityService.class, features);
    }

}
