
package trng.loan.eligibility.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LoanEligibilityService", targetNamespace = "http://www.example.org/LoanEligibilityService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanEligibilityService {


    /**
     * 
     * @param passengerProfileCreateRequest
     * @return
     *     returns trng.loan.eligibility.service.PassengerProfileCreateResponseType
     */
    @WebMethod(action = "http://www.example.org/LoanEligibilityService/createPassengerProfile")
    @WebResult(name = "passengerProfileCreateResponse", targetNamespace = "")
    @RequestWrapper(localName = "createPassengerProfile", targetNamespace = "http://www.example.org/LoanEligibilityService/", className = "trng.loan.eligibility.service.CreatePassengerProfile")
    @ResponseWrapper(localName = "createPassengerProfileResponse", targetNamespace = "http://www.example.org/LoanEligibilityService/", className = "trng.loan.eligibility.service.CreatePassengerProfileResponse")
    public PassengerProfileCreateResponseType createPassengerProfile(
        @WebParam(name = "passengerProfileCreateRequest", targetNamespace = "")
        PassengerProfileCreateRequestType passengerProfileCreateRequest);

    /**
     * 
     * @param passengerProfileGetRequest
     * @return
     *     returns trng.loan.eligibility.service.PassengerProfileGetResponse
     */
    @WebMethod(action = "http://www.example.org/LoanEligibilityService/getPassengerProfile")
    @WebResult(name = "passengerProfileGetResponse", targetNamespace = "")
    @RequestWrapper(localName = "getPassengerProfile", targetNamespace = "http://www.example.org/LoanEligibilityService/", className = "trng.loan.eligibility.service.GetPassengerProfile")
    @ResponseWrapper(localName = "getPassengerProfileResponse", targetNamespace = "http://www.example.org/LoanEligibilityService/", className = "trng.loan.eligibility.service.GetPassengerProfileResponse")
    public PassengerProfileGetResponse getPassengerProfile(
        @WebParam(name = "passengerProfileGetRequest", targetNamespace = "")
        PassengerProfileGetRequestType passengerProfileGetRequest);

    /**
     * 
     * @param passengerProfileUpdateRequest
     * @return
     *     returns trng.loan.eligibility.service.PassengerProfileUpdateResponseType
     */
    @WebMethod(action = "http://www.example.org/LoanEligibilityService/updatePassengerProfile")
    @WebResult(name = "passengerProfileUpdateResponse", targetNamespace = "")
    @RequestWrapper(localName = "updatePassengerProfile", targetNamespace = "http://www.example.org/LoanEligibilityService/", className = "trng.loan.eligibility.service.UpdatePassengerProfile")
    @ResponseWrapper(localName = "updatePassengerProfileResponse", targetNamespace = "http://www.example.org/LoanEligibilityService/", className = "trng.loan.eligibility.service.UpdatePassengerProfileResponse")
    public PassengerProfileUpdateResponseType updatePassengerProfile(
        @WebParam(name = "passengerProfileUpdateRequest", targetNamespace = "")
        PassengerProfileUpdateRequestType passengerProfileUpdateRequest);

    /**
     * 
     * @param passengerProfileDeleteRequest
     * @return
     *     returns trng.loan.eligibility.service.PassengerProfileDeleteResponseType
     */
    @WebMethod(action = "http://www.example.org/LoanEligibilityService/deletePassengerProfile")
    @WebResult(name = "passengerProfileDeleteResponse", targetNamespace = "")
    @RequestWrapper(localName = "deletePassengerProfile", targetNamespace = "http://www.example.org/LoanEligibilityService/", className = "trng.loan.eligibility.service.DeletePassengerProfile")
    @ResponseWrapper(localName = "deletePassengerProfileResponse", targetNamespace = "http://www.example.org/LoanEligibilityService/", className = "trng.loan.eligibility.service.DeletePassengerProfileResponse")
    public PassengerProfileDeleteResponseType deletePassengerProfile(
        @WebParam(name = "passengerProfileDeleteRequest", targetNamespace = "")
        PassengerProfileDeleteRequestType passengerProfileDeleteRequest);

}
